name: Download File
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download File
        run: curl -o /MyConfig/user.yaml https://gitea.com/XIU2/TrackersListCollection/raw/branch/master/all.txt
