name: Create Domain Test File

on:
  push:
    branches:
      - master

jobs:
  create-test-file:
    runs-on: ubuntu-latest
    steps:
      - name: Create Domain Test File
        run: echo "domain:test.com" > domain_test.yaml
      - name: Commit files
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "Create domain_test.yaml file"
          add: "domain_test.yaml"
