name: Create Domain Test File

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  create-test-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Delete old user.yaml
        run: |
          rm MyConfig/user.yaml

      - name: Put together user.yaml
        run: |
          curl -sSL https://raw.githubusercontent.com/DustinWin/Router-Plugins/main/MyConfig/front-user.yaml > temp-fakeip.txt
          curl -sSL https://gitea.com/XIU2/TrackersListCollection/raw/branch/master/all.txt | grep -i "\.[A-Z]" | sed 's/^.*\/\///g' | sed 's/:.*\/.*//g' | sed "s/^/- '/;s/$/'/" >> temp-fakeip.txt
          curl -sSL https://raw.githubusercontent.com/DustinWin/Router-Plugins/main/MyConfig/later-user.yaml >> temp-fakeip.txt

      - name: Create user.yaml
        run: |
          cat temp-fakeip.txt > user.yaml

      - name: Commit changes
        uses: elstudio/actions-git@v2.3.0
        with:
          commit_message: Update user.yaml
          files: MyConfig/user.yaml
          author_name: "github-actions[bot]"
          author_email: "41898282+github-actions[bot]@users.noreply.github.com"
          push: true
