name: Download text from website
on:
  push:
    branches:
      - master

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download text file
        run: |
          curl -o user.yaml -sSL https://gitea.com/XIU2/TrackersListCollection/raw/branch/master/all.txt | grep -i "\.[A-Z]" | grep -v tracker | sed 's/^.*\/\///g' | sed 's/:.*\/.*//g' | sed 's/^/  - "/' | sed 's/$/"/' >> user.txt
