name: Create Domain Test File

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  create-test-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Remove Text between Strings in YAML file
        run: |
          perl -pi -e 's/fake-ip-filter:.*?default-nameserver//g' user.yaml
      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -am "Remove text between strings in user.yaml file"
          git push
