name: Create Domain Test File

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create-test-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: get trackerslist
        run: |
          curl -sSL https://gitea.com/XIU2/TrackersListCollection/raw/branch/master/all.txt | grep -i "\.[A-Z]" | sed 's/^.*\/\///g' | sed 's/:.*\/.*//g' | sed "s/^/- '/;s/$/'/" > temp-fakeip.txt
      - name: Remove Field from File
        run: |
          perl -pi -e 's/fake-ip-filter:.*?default-nameserver//g' user.yaml
      - name: Commit files
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "Remove field from file"
          add: "user.yaml"
