name: Update fake-ip-user.yaml
on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - ".github/workflows/delete-old-workflows.yml"

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@main

    - name: Generate fake-ip-user.yaml
      env:
          SED: sed 's/^/    - /' | sed '/^\s*$/d'
      run: |
        echo "update_version=$(date +%Y-%m-%d)" >> ${GITHUB_ENV}
        mkdir -p ./tmp
        mkdir -p ./fake-ip-config
        rm -f ./fake-ip-config/*
        cat <<EOF > ./tmp/temp-user.txt
        dns:
          enable: true
          prefer-h3: true
          ipv6: true
          listen: 0.0.0.0:1053
          use-hosts: true
          fake-ip-range: 198.18.0.1/16
          enhanced-mode: fake-ip
          fake-ip-filter:
        EOF
          curl -sSL https://raw.githubusercontent.com/juewuy/ShellClash/master/public/fake_ip_filter.list | grep -v "#" | sed "s/.*/'&'/" | ${{ env.SED }} >> ./tmp/temp-user.txt
        cat <<EOF >> ./tmp/temp-user.txt
            - 'adguardteam.github.io'
            - 'anti-ad.net'
          default-nameserver:
            - https://1.12.12.12/dns-query
            - https://223.5.5.5/dns-query
          nameserver:
            - https://doh.pub/dns-query
            - https://dns.alidns.com/dns-query
        EOF
        cat ./tmp/temp-user.txt > ./fake-ip-config/fake-ip-user.yaml
        rm -rf ./tmp

    - name: Commit and push
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add . && git commit -m "更新于 ${update_version}" || exit 0
        git push -f

    - name: Purge jsDelivr CDN cache
      uses: gacts/purge-jsdelivr-cache@v1
      with:
        url: |  
          https://cdn.jsdelivr.net/gh/${{ github.repository }}@main/fake-ip-config/fake-ip-user.yaml
