name: Update fake-ip-user.yaml
on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - ".github/workflows/delete-old-workflows.yml"

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@main

    - name: Generate geo-mode whitelist-mode user.yaml
      env:
          SED: sed 's/^/    - /'
      run: |
        echo "update_version=$(date +%Y-%m-%d)" >> ${GITHUB_ENV}
        mkdir -p ./tmp
        mkdir -p ./dns-bypass/geo-mode/whitelist-mode
        rm -f ./dns-bypass/geo-mode/whitelist-mode/*
        cat <<EOF > ./tmp/temp-user1.txt
        dns:
          enable: true
          prefer-h3: true
          ipv6: true
          listen: 0.0.0.0:1053
          use-hosts: true
          fake-ip-range: 198.18.0.1/16
          enhanced-mode: fake-ip
          fake-ip-filter:
        EOF
        curl -sSL https://raw.githubusercontent.com/juewuy/ShellClash/master/public/fake_ip_filter.list | sed '/^\s*#/d' | sed '/^\s*$/d' | grep -E "\*|\+" | sed "s/.*/'&'/" | ${{ env.SED }} >> ./tmp/temp-user1.txt
        curl -sSL https://raw.githubusercontent.com/juewuy/ShellClash/master/public/fake_ip_filter.list | sed '/^\s*#/d' | sed '/^\s*$/d' | grep -vE "\*|\+" | grep '\.' | ${{ env.SED }} >> ./tmp/temp-user1.txt
        cat <<EOF >> ./tmp/temp-user1.txt
          default-nameserver:
            - https://1.12.12.12/dns-query
            - https://223.5.5.5/dns-query
          nameserver:
            - https://dns.google/dns-query
            - https://cloudflare-dns.com/dns-query
            - https://doh.opendns.com/dns-query
          proxy-server-nameserver:
            - https://doh.pub/dns-query
            - https://dns.alidns.com/dns-query
          nameserver-policy:
            'geosite:microsoft@cn,apple-cn,google-cn,category-games@cn': [https://doh.pub/dns-query, https://dns.alidns.com/dns-query]
            'geosite:cn,private': [https://doh.pub/dns-query, https://dns.alidns.com/dns-query]
        EOF
        cat ./tmp/temp-user1.txt > ./dns-bypass/geo-mode/whitelist-mode/fake-ip-user.yaml
        
    - name: Generate geo-mode blacklist-mode user.yaml
      env:
        SED: sed 's/^/    - /'
      run: |
        mkdir -p ./dns-bypass/geo-mode/blacklist-mode
        rm -f ./dns-bypass/geo-mode/blacklist-mode/*
        cat <<EOF > ./tmp/temp-user2.txt
        dns:
          enable: true
          prefer-h3: true
          ipv6: true
          listen: 0.0.0.0:1053
          use-hosts: true
          fake-ip-range: 198.18.0.1/16
          enhanced-mode: fake-ip
          fake-ip-filter:
        EOF
        curl -sSL https://raw.githubusercontent.com/juewuy/ShellClash/master/public/fake_ip_filter.list | sed '/^\s*#/d' | sed '/^\s*$/d' | grep -E "\*|\+" | sed "s/.*/'&'/" | ${{ env.SED }} >> ./tmp/temp-user2.txt
        curl -sSL https://raw.githubusercontent.com/juewuy/ShellClash/master/public/fake_ip_filter.list | sed '/^\s*#/d' | sed '/^\s*$/d' | grep -vE "\*|\+" | grep '\.' | ${{ env.SED }} >> ./tmp/temp-user2.txt
        cat <<EOF >> ./tmp/temp-user2.txt
          default-nameserver:
            - https://1.12.12.12/dns-query
            - https://223.5.5.5/dns-query
          nameserver:
            - https://doh.pub/dns-query
            - https://dns.alidns.com/dns-query
          nameserver-policy:
            'geosite:gfw': [https://dns.google/dns-query, https://cloudflare-dns.com/dns-query, https://doh.opendns.com/dns-query]
        EOF
        cat ./tmp/temp-user2.txt > ./dns-bypass/geo-mode/blacklist-mode/fake-ip-user.yaml

    - name: Generate ruleset-mode whitelist-mode user.yaml
      env:
          SED: sed 's/^/    - /'
      run: |
        mkdir -p ./dns-bypass/ruleset-mode/whitelist-mode
        rm -f ./dns-bypass/ruleset-mode/whitelist-mode/*
        cat <<EOF > ./tmp/temp-user3.txt
        dns:
          enable: true
          prefer-h3: true
          ipv6: true
          listen: 0.0.0.0:1053
          use-hosts: true
          fake-ip-range: 198.18.0.1/16
          enhanced-mode: fake-ip
          fake-ip-filter:
        EOF
        curl -sSL https://raw.githubusercontent.com/juewuy/ShellClash/master/public/fake_ip_filter.list | sed '/^\s*#/d' | sed '/^\s*$/d' | grep -E "\*|\+" | sed "s/.*/'&'/" | ${{ env.SED }} >> ./tmp/temp-user3.txt
        curl -sSL https://raw.githubusercontent.com/juewuy/ShellClash/master/public/fake_ip_filter.list | sed '/^\s*#/d' | sed '/^\s*$/d' | grep -vE "\*|\+" | grep '\.' | ${{ env.SED }} >> ./tmp/temp-user3.txt
        cat <<EOF >> ./tmp/temp-user3.txt
          default-nameserver:
            - https://1.12.12.12/dns-query
            - https://223.5.5.5/dns-query
          nameserver:
            - https://dns.google/dns-query
            - https://cloudflare-dns.com/dns-query
            - https://doh.opendns.com/dns-query
          proxy-server-nameserver:
            - https://doh.pub/dns-query
            - https://dns.alidns.com/dns-query
          nameserver-policy:
            'rule-set:microsoft-cn,apple-cn,google-cn,games-cn': [https://doh.pub/dns-query, https://dns.alidns.com/dns-query]
            'rule-set:direct,lan': [https://doh.pub/dns-query, https://dns.alidns.com/dns-query]
        EOF
        cat ./tmp/temp-user3.txt > ./dns-bypass/ruleset-mode/whitelist-mode/fake-ip-user.yaml

    - name: Generate ruleset-mode blacklist-mode user.yaml
      env:
          SED: sed 's/^/    - /'
      run: |
        mkdir -p ./dns-bypass/ruleset-mode/blacklist-mode
        rm -f ./dns-bypass/ruleset-mode/blacklist-mode/*
        cat <<EOF > ./tmp/temp-user4.txt
        dns:
          enable: true
          prefer-h3: true
          ipv6: true
          listen: 0.0.0.0:1053
          use-hosts: true
          fake-ip-range: 198.18.0.1/16
          enhanced-mode: fake-ip
          fake-ip-filter:
        EOF
        curl -sSL https://raw.githubusercontent.com/juewuy/ShellClash/master/public/fake_ip_filter.list | sed '/^\s*#/d' | sed '/^\s*$/d' | grep -E "\*|\+" | sed "s/.*/'&'/" | ${{ env.SED }} >> ./tmp/temp-user4.txt
        curl -sSL https://raw.githubusercontent.com/juewuy/ShellClash/master/public/fake_ip_filter.list | sed '/^\s*#/d' | sed '/^\s*$/d' | grep -vE "\*|\+" | grep '\.' | ${{ env.SED }} >> ./tmp/temp-user4.txt
        cat <<EOF >> ./tmp/temp-user4.txt
          default-nameserver:
            - https://1.12.12.12/dns-query
            - https://223.5.5.5/dns-query
          nameserver:
            - https://doh.pub/dns-query
            - https://dns.alidns.com/dns-query
          nameserver-policy:
            'rule-set:proxy': [https://dns.google/dns-query, https://cloudflare-dns.com/dns-query, https://doh.opendns.com/dns-query]
        EOF
        cat ./tmp/temp-user4.txt > ./dns-bypass/ruleset-mode/blacklist-mode/fake-ip-user.yaml
        rm -rf ./tmp

    - name: Commit and push
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add . && git commit -m "更新于 ${update_version}" || exit 0
        git push -f

    - name: Purge jsDelivr CDN cache
      uses: gacts/purge-jsdelivr-cache@v1
      with:
        url: |  
          https://cdn.jsdelivr.net/gh/${{ github.repository }}@main/dns-bypass/geo-mode/whitelist-mode/fake-ip-user.yaml
          https://cdn.jsdelivr.net/gh/${{ github.repository }}@main/dns-bypass/geo-mode/blacklist-mode/fake-ip-user.yaml
          https://cdn.jsdelivr.net/gh/${{ github.repository }}@main/dns-bypass/ruleset-mode/whitelist-mode/fake-ip-user.yaml
          https://cdn.jsdelivr.net/gh/${{ github.repository }}@main/dns-bypass/ruleset-mode/blacklist-mode/fake-ip-user.yaml
